# 数据集路径
data_dict_json_path: outputs/debug_generate2/labels.json
# 模型保存目录和checkpoint路径
checkpoint_path: outputs/save_models/base/gs7656.pkl

val_batch_size: 256
device: cpu

num_workers: 0

model_name: attention